total_radius = 15
base_height = 3
nobbles_num = 7
nobbles_radius = 2
nobbles_height = 4

centerhole_radius = 1.55
centerhex_radus = 3.1
centerhex_height = 2
centerhub_height = 4
centerhub_radius = 4


distance_to_nobbles = total_radius - nobbles_radius
angleA = 360 / nobbles_num
angleARadians = angleA * (3.14159265359 / 180)
  
# this function calculates the third side of a triangle from two sides(a,b) and an angle(A)
get_sideC = (side_a, side_b, angle_A) -> Math.sqrt (Math.pow(side_a, 2) + Math.pow(side_b, 2) - 2 * side_a * side_b * Math.cos(angle_A)) 

#the center hub:
hub = new Cylinder
  h: centerhub_height
  r: centerhub_radius
  center: [0, 0, centerhub_height / 2]

#the nut-trap:
hex = new Cylinder
  h: centerhex_height
  r: centerhex_radus  
  center: [0, 0, centerhub_height - centerhex_height / 2]
  $fn: 6
  
nuttrap = new Cylinder
  h: centerhub_height
  r: centerhole_radius
  center: [0, 0, centerhub_height / 2]
nuttrap = nuttrap.union(hex)
  
#nuttrap = nuttrap.union(
                        
#the base 
base = new Cylinder
  h: base_height
  r: distance_to_nobbles
  center: [0, 0, base_height / 2]

#the little.... knobs.
nobble = new Cylinder
  h: nobbles_height
  r: nobbles_radius
  center: [0, distance_to_nobbles, nobbles_height / 2]

#distance between the nobbles:
nobble_seperation = get_sideC(distance_to_nobbles, distance_to_nobbles, angleARadians)

#the scooped out section between the nobbles:
scallop = new Cylinder
  h: base_height
  r: (nobble_seperation - nobbles_radius) / 2
  center: [0, distance_to_nobbles, base_height / 2]
scallop = scallop.rotate [0, 0, angleA / 2]

#carving the object
shape = base.union(hub)
shape = shape.subtract(nuttrap)
#cutting out the scallops:
i = 0
while i < nobbles_num
  shape = shape.subtract(scallop.rotate [0 ,0 , angleA * i])
  i++
#adding the knobs:
i = 0
while i < nobbles_num
  shape = shape.union(nobble.rotate [0 , 0, angleA * i])
  i++


return shape
